### ISSUE TITLE
Sum of global IR-level GDP != sum of ISO-level GDP 

### ISSUE THREAD

**Issue by StefanKlos** [ClimateImpactLab/impact-common#22] opened 2022-04-21 19:03 UTC
Hi @jrising, 

In mortality, we have 2 different ways of valuing damages: In the paper we scale a region's VSL by its IR-level income, however for integration we scale it by the region's county-level income. Theoretically, the global population average VSL should be the same using the 2 methods, however we found they are off by a tiny magnitude. 

We use the IR-level `SSP{ssp}.nc4` and ISO-level `{var}_{iam}_{ssp}.csv` GDPpc files, both of which are generated using the `GDPpcProvider` [function](https://github.com/ClimateImpactLab/impact-common/blob/87653f98c59125f0a371bb5688af0cc234f450e0/impactcommon/exogenous_economy/gdppc.py) in this repo. 

I did a simple check of where the discrepancies were by comparing each country-year's `sum(ir_pop * ir_gdpppc)` to the `sum(ir_pop) * iso_gdppc` and they are equal in all countries other than SJM, SSD, GRL, ESH and KO-. Each of these receives the global average GDPpc in the ISO file (~7065 in 2010). Each of these has a flat population in each year due to no Landscan data being available. SSD,  GRL, KO-, and ESH have more than one IR within the ISO, but even the single-IR SJM, GRL have different GDPpc values in the IR and ISO level GDPpc files. (I checked the other countries that use the flat population, and found that the rest of them are single-IR countries, but for all them IR GDPpc == ISO GDPpc.)

While it looks like the ISO GDPpc values are from the global average of `/social/baselines/gdppc-merged-nohier.csv`, I believe the IR values go through the `HierarchicalGDPpcProvider` process. 

Tagging @tcarleton so she can follow. 

Thanks!

**Comment by jrising** [comment] 2022-04-22 02:38
That's surprising! I would not have expected `sum(ir_pop * ir_gdpppc) = sum(ir_pop) * iso_gdppc` anywhere. It sounds like either the original nightlight scaling was designed to produce this effect (I don't remember that being a criteria that was applied to the original nightlight method, but this is evidence for it) or the GDPpc files that you are using were post-processed to conform to this.

Also, a correction. I don't think that those countries have a flat population due to no Landscan data. I think it's because they don't show up in the SSP files. I haven't checked though.

If we want to fix this, it's not clear where that should happen. The code in this repo makes no guarantee that the IR and ISO-levels are consistent-- it doesn't even have population data, so it can't.

And it's not clear to me that we want to fix this. Nightlights version 1 does make this guarantee, so this will be fixed in GCP 2.0. If we fix it here, it will make the integration income different from the sector papers. [But, I guess that might already be the case, if there was post-processing on the GDPpc to make the files you use.]

**Comment by brews** [comment] 2024-02-07 17:47
This looks stale so I'm closing this issue. Thank you.

**Closed as completed by brews** 2024-02-07 17:47 UTC
Labels: question
